// Code generated by ent, DO NOT EDIT.

package odometerreading

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Dan6erbond/revline/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldUpdateTime, v))
}

// ReadingKm applies equality check predicate on the "reading_km" field. It's identical to ReadingKmEQ.
func ReadingKm(v float64) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldReadingKm, v))
}

// ReadingTime applies equality check predicate on the "reading_time" field. It's identical to ReadingTimeEQ.
func ReadingTime(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldReadingTime, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldNotes, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLTE(FieldUpdateTime, v))
}

// ReadingKmEQ applies the EQ predicate on the "reading_km" field.
func ReadingKmEQ(v float64) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldReadingKm, v))
}

// ReadingKmNEQ applies the NEQ predicate on the "reading_km" field.
func ReadingKmNEQ(v float64) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNEQ(FieldReadingKm, v))
}

// ReadingKmIn applies the In predicate on the "reading_km" field.
func ReadingKmIn(vs ...float64) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldIn(FieldReadingKm, vs...))
}

// ReadingKmNotIn applies the NotIn predicate on the "reading_km" field.
func ReadingKmNotIn(vs ...float64) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNotIn(FieldReadingKm, vs...))
}

// ReadingKmGT applies the GT predicate on the "reading_km" field.
func ReadingKmGT(v float64) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGT(FieldReadingKm, v))
}

// ReadingKmGTE applies the GTE predicate on the "reading_km" field.
func ReadingKmGTE(v float64) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGTE(FieldReadingKm, v))
}

// ReadingKmLT applies the LT predicate on the "reading_km" field.
func ReadingKmLT(v float64) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLT(FieldReadingKm, v))
}

// ReadingKmLTE applies the LTE predicate on the "reading_km" field.
func ReadingKmLTE(v float64) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLTE(FieldReadingKm, v))
}

// ReadingTimeEQ applies the EQ predicate on the "reading_time" field.
func ReadingTimeEQ(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldReadingTime, v))
}

// ReadingTimeNEQ applies the NEQ predicate on the "reading_time" field.
func ReadingTimeNEQ(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNEQ(FieldReadingTime, v))
}

// ReadingTimeIn applies the In predicate on the "reading_time" field.
func ReadingTimeIn(vs ...time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldIn(FieldReadingTime, vs...))
}

// ReadingTimeNotIn applies the NotIn predicate on the "reading_time" field.
func ReadingTimeNotIn(vs ...time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNotIn(FieldReadingTime, vs...))
}

// ReadingTimeGT applies the GT predicate on the "reading_time" field.
func ReadingTimeGT(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGT(FieldReadingTime, v))
}

// ReadingTimeGTE applies the GTE predicate on the "reading_time" field.
func ReadingTimeGTE(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGTE(FieldReadingTime, v))
}

// ReadingTimeLT applies the LT predicate on the "reading_time" field.
func ReadingTimeLT(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLT(FieldReadingTime, v))
}

// ReadingTimeLTE applies the LTE predicate on the "reading_time" field.
func ReadingTimeLTE(v time.Time) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLTE(FieldReadingTime, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.OdometerReading {
	return predicate.OdometerReading(sql.FieldContainsFold(FieldNotes, v))
}

// HasCar applies the HasEdge predicate on the "car" edge.
func HasCar() predicate.OdometerReading {
	return predicate.OdometerReading(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CarTable, CarColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCarWith applies the HasEdge predicate on the "car" edge with a given conditions (other predicates).
func HasCarWith(preds ...predicate.Car) predicate.OdometerReading {
	return predicate.OdometerReading(func(s *sql.Selector) {
		step := newCarStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFuelUp applies the HasEdge predicate on the "fuel_up" edge.
func HasFuelUp() predicate.OdometerReading {
	return predicate.OdometerReading(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, FuelUpTable, FuelUpColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFuelUpWith applies the HasEdge predicate on the "fuel_up" edge with a given conditions (other predicates).
func HasFuelUpWith(preds ...predicate.FuelUp) predicate.OdometerReading {
	return predicate.OdometerReading(func(s *sql.Selector) {
		step := newFuelUpStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasServiceLog applies the HasEdge predicate on the "service_log" edge.
func HasServiceLog() predicate.OdometerReading {
	return predicate.OdometerReading(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ServiceLogTable, ServiceLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServiceLogWith applies the HasEdge predicate on the "service_log" edge with a given conditions (other predicates).
func HasServiceLogWith(preds ...predicate.ServiceLog) predicate.OdometerReading {
	return predicate.OdometerReading(func(s *sql.Selector) {
		step := newServiceLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OdometerReading) predicate.OdometerReading {
	return predicate.OdometerReading(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OdometerReading) predicate.OdometerReading {
	return predicate.OdometerReading(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OdometerReading) predicate.OdometerReading {
	return predicate.OdometerReading(sql.NotPredicates(p))
}
