// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Dan6erbond/revline/ent/car"
	"github.com/Dan6erbond/revline/ent/document"
	"github.com/Dan6erbond/revline/ent/dynoresult"
	"github.com/Dan6erbond/revline/ent/dynosession"
	"github.com/Dan6erbond/revline/ent/mod"
	"github.com/Dan6erbond/revline/ent/predicate"
	"github.com/google/uuid"
)

// DynoSessionUpdate is the builder for updating DynoSession entities.
type DynoSessionUpdate struct {
	config
	hooks    []Hook
	mutation *DynoSessionMutation
}

// Where appends a list predicates to the DynoSessionUpdate builder.
func (dsu *DynoSessionUpdate) Where(ps ...predicate.DynoSession) *DynoSessionUpdate {
	dsu.mutation.Where(ps...)
	return dsu
}

// SetUpdateTime sets the "update_time" field.
func (dsu *DynoSessionUpdate) SetUpdateTime(t time.Time) *DynoSessionUpdate {
	dsu.mutation.SetUpdateTime(t)
	return dsu
}

// SetTitle sets the "title" field.
func (dsu *DynoSessionUpdate) SetTitle(s string) *DynoSessionUpdate {
	dsu.mutation.SetTitle(s)
	return dsu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (dsu *DynoSessionUpdate) SetNillableTitle(s *string) *DynoSessionUpdate {
	if s != nil {
		dsu.SetTitle(*s)
	}
	return dsu
}

// SetNotes sets the "notes" field.
func (dsu *DynoSessionUpdate) SetNotes(m map[string]interface{}) *DynoSessionUpdate {
	dsu.mutation.SetNotes(m)
	return dsu
}

// ClearNotes clears the value of the "notes" field.
func (dsu *DynoSessionUpdate) ClearNotes() *DynoSessionUpdate {
	dsu.mutation.ClearNotes()
	return dsu
}

// SetCarID sets the "car" edge to the Car entity by ID.
func (dsu *DynoSessionUpdate) SetCarID(id uuid.UUID) *DynoSessionUpdate {
	dsu.mutation.SetCarID(id)
	return dsu
}

// SetCar sets the "car" edge to the Car entity.
func (dsu *DynoSessionUpdate) SetCar(c *Car) *DynoSessionUpdate {
	return dsu.SetCarID(c.ID)
}

// AddResultIDs adds the "results" edge to the DynoResult entity by IDs.
func (dsu *DynoSessionUpdate) AddResultIDs(ids ...uuid.UUID) *DynoSessionUpdate {
	dsu.mutation.AddResultIDs(ids...)
	return dsu
}

// AddResults adds the "results" edges to the DynoResult entity.
func (dsu *DynoSessionUpdate) AddResults(d ...*DynoResult) *DynoSessionUpdate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dsu.AddResultIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (dsu *DynoSessionUpdate) AddDocumentIDs(ids ...uuid.UUID) *DynoSessionUpdate {
	dsu.mutation.AddDocumentIDs(ids...)
	return dsu
}

// AddDocuments adds the "documents" edges to the Document entity.
func (dsu *DynoSessionUpdate) AddDocuments(d ...*Document) *DynoSessionUpdate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dsu.AddDocumentIDs(ids...)
}

// AddModIDs adds the "mods" edge to the Mod entity by IDs.
func (dsu *DynoSessionUpdate) AddModIDs(ids ...uuid.UUID) *DynoSessionUpdate {
	dsu.mutation.AddModIDs(ids...)
	return dsu
}

// AddMods adds the "mods" edges to the Mod entity.
func (dsu *DynoSessionUpdate) AddMods(m ...*Mod) *DynoSessionUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return dsu.AddModIDs(ids...)
}

// Mutation returns the DynoSessionMutation object of the builder.
func (dsu *DynoSessionUpdate) Mutation() *DynoSessionMutation {
	return dsu.mutation
}

// ClearCar clears the "car" edge to the Car entity.
func (dsu *DynoSessionUpdate) ClearCar() *DynoSessionUpdate {
	dsu.mutation.ClearCar()
	return dsu
}

// ClearResults clears all "results" edges to the DynoResult entity.
func (dsu *DynoSessionUpdate) ClearResults() *DynoSessionUpdate {
	dsu.mutation.ClearResults()
	return dsu
}

// RemoveResultIDs removes the "results" edge to DynoResult entities by IDs.
func (dsu *DynoSessionUpdate) RemoveResultIDs(ids ...uuid.UUID) *DynoSessionUpdate {
	dsu.mutation.RemoveResultIDs(ids...)
	return dsu
}

// RemoveResults removes "results" edges to DynoResult entities.
func (dsu *DynoSessionUpdate) RemoveResults(d ...*DynoResult) *DynoSessionUpdate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dsu.RemoveResultIDs(ids...)
}

// ClearDocuments clears all "documents" edges to the Document entity.
func (dsu *DynoSessionUpdate) ClearDocuments() *DynoSessionUpdate {
	dsu.mutation.ClearDocuments()
	return dsu
}

// RemoveDocumentIDs removes the "documents" edge to Document entities by IDs.
func (dsu *DynoSessionUpdate) RemoveDocumentIDs(ids ...uuid.UUID) *DynoSessionUpdate {
	dsu.mutation.RemoveDocumentIDs(ids...)
	return dsu
}

// RemoveDocuments removes "documents" edges to Document entities.
func (dsu *DynoSessionUpdate) RemoveDocuments(d ...*Document) *DynoSessionUpdate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dsu.RemoveDocumentIDs(ids...)
}

// ClearMods clears all "mods" edges to the Mod entity.
func (dsu *DynoSessionUpdate) ClearMods() *DynoSessionUpdate {
	dsu.mutation.ClearMods()
	return dsu
}

// RemoveModIDs removes the "mods" edge to Mod entities by IDs.
func (dsu *DynoSessionUpdate) RemoveModIDs(ids ...uuid.UUID) *DynoSessionUpdate {
	dsu.mutation.RemoveModIDs(ids...)
	return dsu
}

// RemoveMods removes "mods" edges to Mod entities.
func (dsu *DynoSessionUpdate) RemoveMods(m ...*Mod) *DynoSessionUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return dsu.RemoveModIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dsu *DynoSessionUpdate) Save(ctx context.Context) (int, error) {
	dsu.defaults()
	return withHooks(ctx, dsu.sqlSave, dsu.mutation, dsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dsu *DynoSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := dsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dsu *DynoSessionUpdate) Exec(ctx context.Context) error {
	_, err := dsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dsu *DynoSessionUpdate) ExecX(ctx context.Context) {
	if err := dsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dsu *DynoSessionUpdate) defaults() {
	if _, ok := dsu.mutation.UpdateTime(); !ok {
		v := dynosession.UpdateDefaultUpdateTime()
		dsu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dsu *DynoSessionUpdate) check() error {
	if dsu.mutation.CarCleared() && len(dsu.mutation.CarIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DynoSession.car"`)
	}
	return nil
}

func (dsu *DynoSessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := dsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(dynosession.Table, dynosession.Columns, sqlgraph.NewFieldSpec(dynosession.FieldID, field.TypeUUID))
	if ps := dsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dsu.mutation.UpdateTime(); ok {
		_spec.SetField(dynosession.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := dsu.mutation.Title(); ok {
		_spec.SetField(dynosession.FieldTitle, field.TypeString, value)
	}
	if value, ok := dsu.mutation.Notes(); ok {
		_spec.SetField(dynosession.FieldNotes, field.TypeJSON, value)
	}
	if dsu.mutation.NotesCleared() {
		_spec.ClearField(dynosession.FieldNotes, field.TypeJSON)
	}
	if dsu.mutation.CarCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dynosession.CarTable,
			Columns: []string{dynosession.CarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(car.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsu.mutation.CarIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dynosession.CarTable,
			Columns: []string{dynosession.CarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(car.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dsu.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.ResultsTable,
			Columns: []string{dynosession.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dynoresult.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsu.mutation.RemovedResultsIDs(); len(nodes) > 0 && !dsu.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.ResultsTable,
			Columns: []string{dynosession.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dynoresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsu.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.ResultsTable,
			Columns: []string{dynosession.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dynoresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dsu.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.DocumentsTable,
			Columns: []string{dynosession.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsu.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !dsu.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.DocumentsTable,
			Columns: []string{dynosession.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsu.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.DocumentsTable,
			Columns: []string{dynosession.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dsu.mutation.ModsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dynosession.ModsTable,
			Columns: dynosession.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsu.mutation.RemovedModsIDs(); len(nodes) > 0 && !dsu.mutation.ModsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dynosession.ModsTable,
			Columns: dynosession.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsu.mutation.ModsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dynosession.ModsTable,
			Columns: dynosession.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dynosession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dsu.mutation.done = true
	return n, nil
}

// DynoSessionUpdateOne is the builder for updating a single DynoSession entity.
type DynoSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DynoSessionMutation
}

// SetUpdateTime sets the "update_time" field.
func (dsuo *DynoSessionUpdateOne) SetUpdateTime(t time.Time) *DynoSessionUpdateOne {
	dsuo.mutation.SetUpdateTime(t)
	return dsuo
}

// SetTitle sets the "title" field.
func (dsuo *DynoSessionUpdateOne) SetTitle(s string) *DynoSessionUpdateOne {
	dsuo.mutation.SetTitle(s)
	return dsuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (dsuo *DynoSessionUpdateOne) SetNillableTitle(s *string) *DynoSessionUpdateOne {
	if s != nil {
		dsuo.SetTitle(*s)
	}
	return dsuo
}

// SetNotes sets the "notes" field.
func (dsuo *DynoSessionUpdateOne) SetNotes(m map[string]interface{}) *DynoSessionUpdateOne {
	dsuo.mutation.SetNotes(m)
	return dsuo
}

// ClearNotes clears the value of the "notes" field.
func (dsuo *DynoSessionUpdateOne) ClearNotes() *DynoSessionUpdateOne {
	dsuo.mutation.ClearNotes()
	return dsuo
}

// SetCarID sets the "car" edge to the Car entity by ID.
func (dsuo *DynoSessionUpdateOne) SetCarID(id uuid.UUID) *DynoSessionUpdateOne {
	dsuo.mutation.SetCarID(id)
	return dsuo
}

// SetCar sets the "car" edge to the Car entity.
func (dsuo *DynoSessionUpdateOne) SetCar(c *Car) *DynoSessionUpdateOne {
	return dsuo.SetCarID(c.ID)
}

// AddResultIDs adds the "results" edge to the DynoResult entity by IDs.
func (dsuo *DynoSessionUpdateOne) AddResultIDs(ids ...uuid.UUID) *DynoSessionUpdateOne {
	dsuo.mutation.AddResultIDs(ids...)
	return dsuo
}

// AddResults adds the "results" edges to the DynoResult entity.
func (dsuo *DynoSessionUpdateOne) AddResults(d ...*DynoResult) *DynoSessionUpdateOne {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dsuo.AddResultIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (dsuo *DynoSessionUpdateOne) AddDocumentIDs(ids ...uuid.UUID) *DynoSessionUpdateOne {
	dsuo.mutation.AddDocumentIDs(ids...)
	return dsuo
}

// AddDocuments adds the "documents" edges to the Document entity.
func (dsuo *DynoSessionUpdateOne) AddDocuments(d ...*Document) *DynoSessionUpdateOne {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dsuo.AddDocumentIDs(ids...)
}

// AddModIDs adds the "mods" edge to the Mod entity by IDs.
func (dsuo *DynoSessionUpdateOne) AddModIDs(ids ...uuid.UUID) *DynoSessionUpdateOne {
	dsuo.mutation.AddModIDs(ids...)
	return dsuo
}

// AddMods adds the "mods" edges to the Mod entity.
func (dsuo *DynoSessionUpdateOne) AddMods(m ...*Mod) *DynoSessionUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return dsuo.AddModIDs(ids...)
}

// Mutation returns the DynoSessionMutation object of the builder.
func (dsuo *DynoSessionUpdateOne) Mutation() *DynoSessionMutation {
	return dsuo.mutation
}

// ClearCar clears the "car" edge to the Car entity.
func (dsuo *DynoSessionUpdateOne) ClearCar() *DynoSessionUpdateOne {
	dsuo.mutation.ClearCar()
	return dsuo
}

// ClearResults clears all "results" edges to the DynoResult entity.
func (dsuo *DynoSessionUpdateOne) ClearResults() *DynoSessionUpdateOne {
	dsuo.mutation.ClearResults()
	return dsuo
}

// RemoveResultIDs removes the "results" edge to DynoResult entities by IDs.
func (dsuo *DynoSessionUpdateOne) RemoveResultIDs(ids ...uuid.UUID) *DynoSessionUpdateOne {
	dsuo.mutation.RemoveResultIDs(ids...)
	return dsuo
}

// RemoveResults removes "results" edges to DynoResult entities.
func (dsuo *DynoSessionUpdateOne) RemoveResults(d ...*DynoResult) *DynoSessionUpdateOne {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dsuo.RemoveResultIDs(ids...)
}

// ClearDocuments clears all "documents" edges to the Document entity.
func (dsuo *DynoSessionUpdateOne) ClearDocuments() *DynoSessionUpdateOne {
	dsuo.mutation.ClearDocuments()
	return dsuo
}

// RemoveDocumentIDs removes the "documents" edge to Document entities by IDs.
func (dsuo *DynoSessionUpdateOne) RemoveDocumentIDs(ids ...uuid.UUID) *DynoSessionUpdateOne {
	dsuo.mutation.RemoveDocumentIDs(ids...)
	return dsuo
}

// RemoveDocuments removes "documents" edges to Document entities.
func (dsuo *DynoSessionUpdateOne) RemoveDocuments(d ...*Document) *DynoSessionUpdateOne {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dsuo.RemoveDocumentIDs(ids...)
}

// ClearMods clears all "mods" edges to the Mod entity.
func (dsuo *DynoSessionUpdateOne) ClearMods() *DynoSessionUpdateOne {
	dsuo.mutation.ClearMods()
	return dsuo
}

// RemoveModIDs removes the "mods" edge to Mod entities by IDs.
func (dsuo *DynoSessionUpdateOne) RemoveModIDs(ids ...uuid.UUID) *DynoSessionUpdateOne {
	dsuo.mutation.RemoveModIDs(ids...)
	return dsuo
}

// RemoveMods removes "mods" edges to Mod entities.
func (dsuo *DynoSessionUpdateOne) RemoveMods(m ...*Mod) *DynoSessionUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return dsuo.RemoveModIDs(ids...)
}

// Where appends a list predicates to the DynoSessionUpdate builder.
func (dsuo *DynoSessionUpdateOne) Where(ps ...predicate.DynoSession) *DynoSessionUpdateOne {
	dsuo.mutation.Where(ps...)
	return dsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dsuo *DynoSessionUpdateOne) Select(field string, fields ...string) *DynoSessionUpdateOne {
	dsuo.fields = append([]string{field}, fields...)
	return dsuo
}

// Save executes the query and returns the updated DynoSession entity.
func (dsuo *DynoSessionUpdateOne) Save(ctx context.Context) (*DynoSession, error) {
	dsuo.defaults()
	return withHooks(ctx, dsuo.sqlSave, dsuo.mutation, dsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dsuo *DynoSessionUpdateOne) SaveX(ctx context.Context) *DynoSession {
	node, err := dsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dsuo *DynoSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := dsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dsuo *DynoSessionUpdateOne) ExecX(ctx context.Context) {
	if err := dsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dsuo *DynoSessionUpdateOne) defaults() {
	if _, ok := dsuo.mutation.UpdateTime(); !ok {
		v := dynosession.UpdateDefaultUpdateTime()
		dsuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dsuo *DynoSessionUpdateOne) check() error {
	if dsuo.mutation.CarCleared() && len(dsuo.mutation.CarIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DynoSession.car"`)
	}
	return nil
}

func (dsuo *DynoSessionUpdateOne) sqlSave(ctx context.Context) (_node *DynoSession, err error) {
	if err := dsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dynosession.Table, dynosession.Columns, sqlgraph.NewFieldSpec(dynosession.FieldID, field.TypeUUID))
	id, ok := dsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DynoSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dynosession.FieldID)
		for _, f := range fields {
			if !dynosession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dynosession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dsuo.mutation.UpdateTime(); ok {
		_spec.SetField(dynosession.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := dsuo.mutation.Title(); ok {
		_spec.SetField(dynosession.FieldTitle, field.TypeString, value)
	}
	if value, ok := dsuo.mutation.Notes(); ok {
		_spec.SetField(dynosession.FieldNotes, field.TypeJSON, value)
	}
	if dsuo.mutation.NotesCleared() {
		_spec.ClearField(dynosession.FieldNotes, field.TypeJSON)
	}
	if dsuo.mutation.CarCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dynosession.CarTable,
			Columns: []string{dynosession.CarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(car.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsuo.mutation.CarIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dynosession.CarTable,
			Columns: []string{dynosession.CarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(car.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dsuo.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.ResultsTable,
			Columns: []string{dynosession.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dynoresult.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsuo.mutation.RemovedResultsIDs(); len(nodes) > 0 && !dsuo.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.ResultsTable,
			Columns: []string{dynosession.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dynoresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsuo.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.ResultsTable,
			Columns: []string{dynosession.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dynoresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dsuo.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.DocumentsTable,
			Columns: []string{dynosession.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsuo.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !dsuo.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.DocumentsTable,
			Columns: []string{dynosession.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsuo.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dynosession.DocumentsTable,
			Columns: []string{dynosession.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if dsuo.mutation.ModsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dynosession.ModsTable,
			Columns: dynosession.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsuo.mutation.RemovedModsIDs(); len(nodes) > 0 && !dsuo.mutation.ModsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dynosession.ModsTable,
			Columns: dynosession.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dsuo.mutation.ModsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   dynosession.ModsTable,
			Columns: dynosession.ModsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DynoSession{config: dsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dynosession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	dsuo.mutation.done = true
	return _node, nil
}
