// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Dan6erbond/revline/ent/car"
	"github.com/Dan6erbond/revline/ent/fuelup"
	"github.com/Dan6erbond/revline/ent/odometerreading"
	"github.com/Dan6erbond/revline/ent/predicate"
	"github.com/Dan6erbond/revline/ent/servicelog"
	"github.com/google/uuid"
)

// OdometerReadingQuery is the builder for querying OdometerReading entities.
type OdometerReadingQuery struct {
	config
	ctx            *QueryContext
	order          []odometerreading.OrderOption
	inters         []Interceptor
	predicates     []predicate.OdometerReading
	withCar        *CarQuery
	withFuelUp     *FuelUpQuery
	withServiceLog *ServiceLogQuery
	withFKs        bool
	modifiers      []func(*sql.Selector)
	loadTotal      []func(context.Context, []*OdometerReading) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OdometerReadingQuery builder.
func (orq *OdometerReadingQuery) Where(ps ...predicate.OdometerReading) *OdometerReadingQuery {
	orq.predicates = append(orq.predicates, ps...)
	return orq
}

// Limit the number of records to be returned by this query.
func (orq *OdometerReadingQuery) Limit(limit int) *OdometerReadingQuery {
	orq.ctx.Limit = &limit
	return orq
}

// Offset to start from.
func (orq *OdometerReadingQuery) Offset(offset int) *OdometerReadingQuery {
	orq.ctx.Offset = &offset
	return orq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (orq *OdometerReadingQuery) Unique(unique bool) *OdometerReadingQuery {
	orq.ctx.Unique = &unique
	return orq
}

// Order specifies how the records should be ordered.
func (orq *OdometerReadingQuery) Order(o ...odometerreading.OrderOption) *OdometerReadingQuery {
	orq.order = append(orq.order, o...)
	return orq
}

// QueryCar chains the current query on the "car" edge.
func (orq *OdometerReadingQuery) QueryCar() *CarQuery {
	query := (&CarClient{config: orq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := orq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := orq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(odometerreading.Table, odometerreading.FieldID, selector),
			sqlgraph.To(car.Table, car.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, odometerreading.CarTable, odometerreading.CarColumn),
		)
		fromU = sqlgraph.SetNeighbors(orq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFuelUp chains the current query on the "fuel_up" edge.
func (orq *OdometerReadingQuery) QueryFuelUp() *FuelUpQuery {
	query := (&FuelUpClient{config: orq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := orq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := orq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(odometerreading.Table, odometerreading.FieldID, selector),
			sqlgraph.To(fuelup.Table, fuelup.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, odometerreading.FuelUpTable, odometerreading.FuelUpColumn),
		)
		fromU = sqlgraph.SetNeighbors(orq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryServiceLog chains the current query on the "service_log" edge.
func (orq *OdometerReadingQuery) QueryServiceLog() *ServiceLogQuery {
	query := (&ServiceLogClient{config: orq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := orq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := orq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(odometerreading.Table, odometerreading.FieldID, selector),
			sqlgraph.To(servicelog.Table, servicelog.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, odometerreading.ServiceLogTable, odometerreading.ServiceLogColumn),
		)
		fromU = sqlgraph.SetNeighbors(orq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OdometerReading entity from the query.
// Returns a *NotFoundError when no OdometerReading was found.
func (orq *OdometerReadingQuery) First(ctx context.Context) (*OdometerReading, error) {
	nodes, err := orq.Limit(1).All(setContextOp(ctx, orq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{odometerreading.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (orq *OdometerReadingQuery) FirstX(ctx context.Context) *OdometerReading {
	node, err := orq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OdometerReading ID from the query.
// Returns a *NotFoundError when no OdometerReading ID was found.
func (orq *OdometerReadingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = orq.Limit(1).IDs(setContextOp(ctx, orq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{odometerreading.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (orq *OdometerReadingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := orq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OdometerReading entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OdometerReading entity is found.
// Returns a *NotFoundError when no OdometerReading entities are found.
func (orq *OdometerReadingQuery) Only(ctx context.Context) (*OdometerReading, error) {
	nodes, err := orq.Limit(2).All(setContextOp(ctx, orq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{odometerreading.Label}
	default:
		return nil, &NotSingularError{odometerreading.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (orq *OdometerReadingQuery) OnlyX(ctx context.Context) *OdometerReading {
	node, err := orq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OdometerReading ID in the query.
// Returns a *NotSingularError when more than one OdometerReading ID is found.
// Returns a *NotFoundError when no entities are found.
func (orq *OdometerReadingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = orq.Limit(2).IDs(setContextOp(ctx, orq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{odometerreading.Label}
	default:
		err = &NotSingularError{odometerreading.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (orq *OdometerReadingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := orq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OdometerReadings.
func (orq *OdometerReadingQuery) All(ctx context.Context) ([]*OdometerReading, error) {
	ctx = setContextOp(ctx, orq.ctx, ent.OpQueryAll)
	if err := orq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OdometerReading, *OdometerReadingQuery]()
	return withInterceptors[[]*OdometerReading](ctx, orq, qr, orq.inters)
}

// AllX is like All, but panics if an error occurs.
func (orq *OdometerReadingQuery) AllX(ctx context.Context) []*OdometerReading {
	nodes, err := orq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OdometerReading IDs.
func (orq *OdometerReadingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if orq.ctx.Unique == nil && orq.path != nil {
		orq.Unique(true)
	}
	ctx = setContextOp(ctx, orq.ctx, ent.OpQueryIDs)
	if err = orq.Select(odometerreading.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (orq *OdometerReadingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := orq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (orq *OdometerReadingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, orq.ctx, ent.OpQueryCount)
	if err := orq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, orq, querierCount[*OdometerReadingQuery](), orq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (orq *OdometerReadingQuery) CountX(ctx context.Context) int {
	count, err := orq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (orq *OdometerReadingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, orq.ctx, ent.OpQueryExist)
	switch _, err := orq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (orq *OdometerReadingQuery) ExistX(ctx context.Context) bool {
	exist, err := orq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OdometerReadingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (orq *OdometerReadingQuery) Clone() *OdometerReadingQuery {
	if orq == nil {
		return nil
	}
	return &OdometerReadingQuery{
		config:         orq.config,
		ctx:            orq.ctx.Clone(),
		order:          append([]odometerreading.OrderOption{}, orq.order...),
		inters:         append([]Interceptor{}, orq.inters...),
		predicates:     append([]predicate.OdometerReading{}, orq.predicates...),
		withCar:        orq.withCar.Clone(),
		withFuelUp:     orq.withFuelUp.Clone(),
		withServiceLog: orq.withServiceLog.Clone(),
		// clone intermediate query.
		sql:  orq.sql.Clone(),
		path: orq.path,
	}
}

// WithCar tells the query-builder to eager-load the nodes that are connected to
// the "car" edge. The optional arguments are used to configure the query builder of the edge.
func (orq *OdometerReadingQuery) WithCar(opts ...func(*CarQuery)) *OdometerReadingQuery {
	query := (&CarClient{config: orq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	orq.withCar = query
	return orq
}

// WithFuelUp tells the query-builder to eager-load the nodes that are connected to
// the "fuel_up" edge. The optional arguments are used to configure the query builder of the edge.
func (orq *OdometerReadingQuery) WithFuelUp(opts ...func(*FuelUpQuery)) *OdometerReadingQuery {
	query := (&FuelUpClient{config: orq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	orq.withFuelUp = query
	return orq
}

// WithServiceLog tells the query-builder to eager-load the nodes that are connected to
// the "service_log" edge. The optional arguments are used to configure the query builder of the edge.
func (orq *OdometerReadingQuery) WithServiceLog(opts ...func(*ServiceLogQuery)) *OdometerReadingQuery {
	query := (&ServiceLogClient{config: orq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	orq.withServiceLog = query
	return orq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OdometerReading.Query().
//		GroupBy(odometerreading.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (orq *OdometerReadingQuery) GroupBy(field string, fields ...string) *OdometerReadingGroupBy {
	orq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OdometerReadingGroupBy{build: orq}
	grbuild.flds = &orq.ctx.Fields
	grbuild.label = odometerreading.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.OdometerReading.Query().
//		Select(odometerreading.FieldCreateTime).
//		Scan(ctx, &v)
func (orq *OdometerReadingQuery) Select(fields ...string) *OdometerReadingSelect {
	orq.ctx.Fields = append(orq.ctx.Fields, fields...)
	sbuild := &OdometerReadingSelect{OdometerReadingQuery: orq}
	sbuild.label = odometerreading.Label
	sbuild.flds, sbuild.scan = &orq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OdometerReadingSelect configured with the given aggregations.
func (orq *OdometerReadingQuery) Aggregate(fns ...AggregateFunc) *OdometerReadingSelect {
	return orq.Select().Aggregate(fns...)
}

func (orq *OdometerReadingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range orq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, orq); err != nil {
				return err
			}
		}
	}
	for _, f := range orq.ctx.Fields {
		if !odometerreading.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if orq.path != nil {
		prev, err := orq.path(ctx)
		if err != nil {
			return err
		}
		orq.sql = prev
	}
	return nil
}

func (orq *OdometerReadingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OdometerReading, error) {
	var (
		nodes       = []*OdometerReading{}
		withFKs     = orq.withFKs
		_spec       = orq.querySpec()
		loadedTypes = [3]bool{
			orq.withCar != nil,
			orq.withFuelUp != nil,
			orq.withServiceLog != nil,
		}
	)
	if orq.withCar != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, odometerreading.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OdometerReading).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OdometerReading{config: orq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(orq.modifiers) > 0 {
		_spec.Modifiers = orq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, orq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := orq.withCar; query != nil {
		if err := orq.loadCar(ctx, query, nodes, nil,
			func(n *OdometerReading, e *Car) { n.Edges.Car = e }); err != nil {
			return nil, err
		}
	}
	if query := orq.withFuelUp; query != nil {
		if err := orq.loadFuelUp(ctx, query, nodes, nil,
			func(n *OdometerReading, e *FuelUp) { n.Edges.FuelUp = e }); err != nil {
			return nil, err
		}
	}
	if query := orq.withServiceLog; query != nil {
		if err := orq.loadServiceLog(ctx, query, nodes, nil,
			func(n *OdometerReading, e *ServiceLog) { n.Edges.ServiceLog = e }); err != nil {
			return nil, err
		}
	}
	for i := range orq.loadTotal {
		if err := orq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (orq *OdometerReadingQuery) loadCar(ctx context.Context, query *CarQuery, nodes []*OdometerReading, init func(*OdometerReading), assign func(*OdometerReading, *Car)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*OdometerReading)
	for i := range nodes {
		if nodes[i].car_odometer_readings == nil {
			continue
		}
		fk := *nodes[i].car_odometer_readings
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(car.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "car_odometer_readings" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (orq *OdometerReadingQuery) loadFuelUp(ctx context.Context, query *FuelUpQuery, nodes []*OdometerReading, init func(*OdometerReading), assign func(*OdometerReading, *FuelUp)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*OdometerReading)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.FuelUp(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(odometerreading.FuelUpColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.odometer_reading_fuel_up
		if fk == nil {
			return fmt.Errorf(`foreign-key "odometer_reading_fuel_up" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "odometer_reading_fuel_up" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (orq *OdometerReadingQuery) loadServiceLog(ctx context.Context, query *ServiceLogQuery, nodes []*OdometerReading, init func(*OdometerReading), assign func(*OdometerReading, *ServiceLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*OdometerReading)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.ServiceLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(odometerreading.ServiceLogColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.odometer_reading_service_log
		if fk == nil {
			return fmt.Errorf(`foreign-key "odometer_reading_service_log" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "odometer_reading_service_log" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (orq *OdometerReadingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := orq.querySpec()
	if len(orq.modifiers) > 0 {
		_spec.Modifiers = orq.modifiers
	}
	_spec.Node.Columns = orq.ctx.Fields
	if len(orq.ctx.Fields) > 0 {
		_spec.Unique = orq.ctx.Unique != nil && *orq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, orq.driver, _spec)
}

func (orq *OdometerReadingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(odometerreading.Table, odometerreading.Columns, sqlgraph.NewFieldSpec(odometerreading.FieldID, field.TypeUUID))
	_spec.From = orq.sql
	if unique := orq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if orq.path != nil {
		_spec.Unique = true
	}
	if fields := orq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, odometerreading.FieldID)
		for i := range fields {
			if fields[i] != odometerreading.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := orq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := orq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := orq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := orq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (orq *OdometerReadingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(orq.driver.Dialect())
	t1 := builder.Table(odometerreading.Table)
	columns := orq.ctx.Fields
	if len(columns) == 0 {
		columns = odometerreading.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if orq.sql != nil {
		selector = orq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if orq.ctx.Unique != nil && *orq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range orq.predicates {
		p(selector)
	}
	for _, p := range orq.order {
		p(selector)
	}
	if offset := orq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := orq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OdometerReadingGroupBy is the group-by builder for OdometerReading entities.
type OdometerReadingGroupBy struct {
	selector
	build *OdometerReadingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (orgb *OdometerReadingGroupBy) Aggregate(fns ...AggregateFunc) *OdometerReadingGroupBy {
	orgb.fns = append(orgb.fns, fns...)
	return orgb
}

// Scan applies the selector query and scans the result into the given value.
func (orgb *OdometerReadingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, orgb.build.ctx, ent.OpQueryGroupBy)
	if err := orgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OdometerReadingQuery, *OdometerReadingGroupBy](ctx, orgb.build, orgb, orgb.build.inters, v)
}

func (orgb *OdometerReadingGroupBy) sqlScan(ctx context.Context, root *OdometerReadingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(orgb.fns))
	for _, fn := range orgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*orgb.flds)+len(orgb.fns))
		for _, f := range *orgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*orgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := orgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OdometerReadingSelect is the builder for selecting fields of OdometerReading entities.
type OdometerReadingSelect struct {
	*OdometerReadingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ors *OdometerReadingSelect) Aggregate(fns ...AggregateFunc) *OdometerReadingSelect {
	ors.fns = append(ors.fns, fns...)
	return ors
}

// Scan applies the selector query and scans the result into the given value.
func (ors *OdometerReadingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ors.ctx, ent.OpQuerySelect)
	if err := ors.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OdometerReadingQuery, *OdometerReadingSelect](ctx, ors.OdometerReadingQuery, ors, ors.inters, v)
}

func (ors *OdometerReadingSelect) sqlScan(ctx context.Context, root *OdometerReadingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ors.fns))
	for _, fn := range ors.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ors.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ors.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
