// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Dan6erbond/revline/ent/predicate"
	"github.com/Dan6erbond/revline/ent/serviceschedule"
)

// ServiceScheduleDelete is the builder for deleting a ServiceSchedule entity.
type ServiceScheduleDelete struct {
	config
	hooks    []Hook
	mutation *ServiceScheduleMutation
}

// Where appends a list predicates to the ServiceScheduleDelete builder.
func (ssd *ServiceScheduleDelete) Where(ps ...predicate.ServiceSchedule) *ServiceScheduleDelete {
	ssd.mutation.Where(ps...)
	return ssd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ssd *ServiceScheduleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ssd.sqlExec, ssd.mutation, ssd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ssd *ServiceScheduleDelete) ExecX(ctx context.Context) int {
	n, err := ssd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ssd *ServiceScheduleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(serviceschedule.Table, sqlgraph.NewFieldSpec(serviceschedule.FieldID, field.TypeUUID))
	if ps := ssd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ssd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ssd.mutation.done = true
	return affected, err
}

// ServiceScheduleDeleteOne is the builder for deleting a single ServiceSchedule entity.
type ServiceScheduleDeleteOne struct {
	ssd *ServiceScheduleDelete
}

// Where appends a list predicates to the ServiceScheduleDelete builder.
func (ssdo *ServiceScheduleDeleteOne) Where(ps ...predicate.ServiceSchedule) *ServiceScheduleDeleteOne {
	ssdo.ssd.mutation.Where(ps...)
	return ssdo
}

// Exec executes the deletion query.
func (ssdo *ServiceScheduleDeleteOne) Exec(ctx context.Context) error {
	n, err := ssdo.ssd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{serviceschedule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ssdo *ServiceScheduleDeleteOne) ExecX(ctx context.Context) {
	if err := ssdo.Exec(ctx); err != nil {
		panic(err)
	}
}
